Browser=chrome
headless=false

loginurl=https://www.flipkart.com/
login=https://www.flipkart.com/account/login

chromeDriverProperty=webdriver.chrome.driver
chromeDriverPath=.\\Drivers\\chromedriver.exe

firefoxDriverProperty=webdriver.gecko.driver
firefoxDriverPath=.\\Drivers\\geckodriver.exe

edgeDriverProperty=webdriver.edge.driver
edgeDriverPath=.\\Drivers\\msedgedriver.exe

implicitwait5=5
implicitwait10=10
implicitwait15=15
implicitwait20=20